version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: llm-eval-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --tcp-keepalive 60 --timeout 300
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - llm-eval-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: llm-eval-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-}
      - HTTP_USER=admin
      - HTTP_PASSWORD=${REDIS_UI_PASSWORD:-admin123}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - llm-eval-network
    profiles:
      - dev
      - debug

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: llm-eval-redis-exporter
    restart: unless-stopped
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - llm-eval-network
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local

networks:
  llm-eval-network:
    driver: bridge 